-- task_4.sql
-- Prints a full description of the 'books' table using INFORMATION_SCHEMA
-- The database name will be provided by the mysql command (so DATABASE() is used)

SELECT
  COLUMN_NAME,
  COLUMN_TYPE,
  IS_NULLABLE,
  COLUMN_DEFAULT,
  COLUMN_KEY,
  EXTRA,
  CHARACTER_SET_NAME,
  COLLATION_NAME,
  COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'books'
ORDER BY ORDINAL_POSITION;

SELECT
  TC.CONSTRAINT_NAME,
  TC.CONSTRAINT_TYPE,
  KCU.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
  ON TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME
  AND TC.TABLE_SCHEMA = KCU.TABLE_SCHEMA
  AND TC.TABLE_NAME = KCU.TABLE_NAME
WHERE TC.TABLE_SCHEMA = DATABASE()
  AND TC.TABLE_NAME = 'books'
ORDER BY TC.CONSTRAINT_TYPE, KCU.ORDINAL_POSITION;

SELECT
  KCU.CONSTRAINT_NAME,
  KCU.COLUMN_NAME,
  KCU.REFERENCED_TABLE_NAME,
  KCU.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
WHERE KCU.TABLE_SCHEMA = DATABASE()
  AND KCU.TABLE_NAME = 'books'
  AND KCU.REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY KCU.CONSTRAINT_NAME, KCU.ORDINAL_POSITION;
