-- task_4.sql
-- Print full description of table 'books' without using DESCRIBE or EXPLAIN.
SELECT
  C.COLUMN_NAME AS 'Field',
  C.COLUMN_TYPE AS 'Type',
  C.IS_NULLABLE AS 'Null',
  CASE
    WHEN PK.COLUMN_NAME IS NOT NULL THEN 'PRI'
    WHEN IDX.COLUMN_NAME IS NOT NULL THEN 'MUL'
    ELSE ''
  END AS `Key`,
  C.COLUMN_DEFAULT AS 'Default',
  C.EXTRA AS 'Extra'
FROM INFORMATION_SCHEMA.COLUMNS C
LEFT JOIN (
  SELECT COLUMN_NAME
  FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'books'
    AND CONSTRAINT_NAME = 'PRIMARY'
) PK ON PK.COLUMN_NAME = C.COLUMN_NAME
LEFT JOIN (
  SELECT DISTINCT COLUMN_NAME
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'books'
    AND INDEX_NAME != 'PRIMARY'
) IDX ON IDX.COLUMN_NAME = C.COLUMN_NAME
WHERE C.TABLE_SCHEMA = DATABASE()
  AND C.TABLE_NAME = 'books'
ORDER BY C.ORDINAL_POSITION;
